// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7kPeb2evD2OCstQR4GsO23bDONLrKiBQ',
    appId: '1:409584392501:web:937b5e6743b11a07f2d47c',
    messagingSenderId: '409584392501',
    projectId: 'chapapp-9d150',
    authDomain: 'chapapp-9d150.firebaseapp.com',
    storageBucket: 'chapapp-9d150.appspot.com',
    measurementId: 'G-JNQMDV9GJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuhZy_a-COJMFbTN9qjaxVwWIhChPFJDY',
    appId: '1:409584392501:android:8b301779c236ffe0f2d47c',
    messagingSenderId: '409584392501',
    projectId: 'chapapp-9d150',
    storageBucket: 'chapapp-9d150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBak8QlQYDpx2l5yVmcWA5c-DIplKBH6wk',
    appId: '1:409584392501:ios:9db088823b3d4bd7f2d47c',
    messagingSenderId: '409584392501',
    projectId: 'chapapp-9d150',
    storageBucket: 'chapapp-9d150.appspot.com',
    iosClientId: '409584392501-jgo2rjvbmskol0b2bjhisg6scilnaj41.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBak8QlQYDpx2l5yVmcWA5c-DIplKBH6wk',
    appId: '1:409584392501:ios:9db088823b3d4bd7f2d47c',
    messagingSenderId: '409584392501',
    projectId: 'chapapp-9d150',
    storageBucket: 'chapapp-9d150.appspot.com',
    iosClientId: '409584392501-jgo2rjvbmskol0b2bjhisg6scilnaj41.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
