// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjyy4ZAC_1fm9z-uQ27kPmxylKj-aVu7U',
    appId: '1:999212379852:web:a24af79557cde324199c69',
    messagingSenderId: '999212379852',
    projectId: 'message-ca544',
    authDomain: 'message-ca544.firebaseapp.com',
    databaseURL: 'https://message-ca544-default-rtdb.firebaseio.com',
    storageBucket: 'message-ca544.appspot.com',
    measurementId: 'G-YZP2RYPFX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUIrr-liyeMc0221qktnvXwFdv8YzGsbM',
    appId: '1:999212379852:android:3fd0c0587ff88a52199c69',
    messagingSenderId: '999212379852',
    projectId: 'message-ca544',
    databaseURL: 'https://message-ca544-default-rtdb.firebaseio.com',
    storageBucket: 'message-ca544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5ez0pNCxUzfa5KowWAGkK9a1EkPxo3o',
    appId: '1:999212379852:ios:ef0864deab563f75199c69',
    messagingSenderId: '999212379852',
    projectId: 'message-ca544',
    databaseURL: 'https://message-ca544-default-rtdb.firebaseio.com',
    storageBucket: 'message-ca544.appspot.com',
    iosClientId: '999212379852-4e423f1tlf0atrc4o0at7g1cgu2aevi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5ez0pNCxUzfa5KowWAGkK9a1EkPxo3o',
    appId: '1:999212379852:ios:ef0864deab563f75199c69',
    messagingSenderId: '999212379852',
    projectId: 'message-ca544',
    databaseURL: 'https://message-ca544-default-rtdb.firebaseio.com',
    storageBucket: 'message-ca544.appspot.com',
    iosClientId: '999212379852-4e423f1tlf0atrc4o0at7g1cgu2aevi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.message',
  );
}
